service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  # profile: femasters
  region: us-west-1
  stage: dev

plugins:
  - serverless-offline

function:
  hello:
    handler: src/helloworld.handler
