service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  # profile: femasters ## if it is configured at all
  region: us-west-2
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: src/api/api.handler
    events:
      - http: ANY /
      - http: 'ANY /{param+}'


  # todos:
  #   handler: src/api/todos.handler
  #   events:
  #     - http:
  #         path: /todo
  #         method: GET


  # todo:
  #   handler: src/api/todo.handler
  #   events:
  #     - http:
  #         path: /todo/{id}
  #         method: GET
  #         request: # in some cases id should be allowed to be used explicitly
  #           parameters:
  #             id: true

